### ISSUE TITLE
Oneshot read/write

### ISSUE THREAD

**Issue by svnhub** [Webstrates/file-system#6]
A low-prio feature request for three commandline arguments that instruct the file-system script how to behave in one-way scenarios where either the webstrate or the file is "authoritative".

--readonly : to only ever read the current webstrate into the file regardless of any local changes to the file made by other programs
--writeonly: to only write the file into the webstrate but ignore any changes made to the webstrate
--oneshot: immediately exit after updating either the file or the webstrate rather than continuing to monitor the file/webstrate.

The primary use-case for this will be to embed the file-system script into continuous integration servers or similar scripting environments where webstrates can be either deployed or archived automatically.

**Comment by kbadk** [comment]
Great ideas, I'll definitely implement those.

But just to clarify about the `--writeonly` parameter: If we're not listening for changes, any time we save the document (with our own updates in it), we'll effectively be overwriting what anybody else has been doing to the DOM. Is that the intention?

**Comment by svnhub** [comment]
Exactly - and the same in the other direction with the --readonly one.
Maybe also name them something along the lines of --to-webstrate-only and --from-webstrate-only to avoid confusion about whether it is the file or the webstrate that is being read/written.

**Comment by kbadk** [comment]
This was added with 88dbb36d08ad97792dbe4b6ed90dace9e81aa262.
