### ISSUE TITLE
File change detection corrupts file

### ISSUE THREAD

**Issue by svnhub** [Webstrates/file-system#8]
For large files where it takes more than a few nanosecs to save the file from an editor, the file-system script will detect that the file has changed already while it is being saved. It will then read the (halfway written) file and construct a partial DOM from it and write back the file to the file system. The file is now no longer correct and much smaller than it was supposed to be. Both the webstrate and the file is now corrupt.

In our testcase it took 3,8ms to commit a 300KB file to disk but a change was detected by the script already after the first 8KB were written and immediately after the editor was done saving the file the file-system script truncates the file to around 8KB albeit with a "valid" DOM tree.

The issue can be worked around from the editor by writing to a tmp file and then atomically replacing the file system document file with the new copy, but not all editors do this. Most simply rewrite the existing file.

**Comment by svnhub** [comment]
The workaround above did not work reliably. Very often the script would simply stop getting update notifications after a while.

Instead, hacking in a check that waits until 100ms after the last file system change notification before reading the html seems to do the trick and gets the entire file every time.

**Comment by kbadk** [comment]
Is this still a problem?
