### ISSUE TITLE
HTML entities are acting up

### ISSUE THREAD

**Issue by svnhub** [Webstrates/file-system#9]
A test-case with the document in the bottom of this issue displays as
`© & > < æ ø å`
locally but displays as 
`&copy; & > < &aelig; &oslash; &aring;`
when uploaded via the filesystem script. Note that ampersand, greater than and less than are correctly shown but not other entities; the other entities are doubly escaped.

```
<!DOCTYPE html>
<html>
    <head></head>
    <body>&copy; &amp; &gt; &lt; &aelig; &oslash; &aring;</body>
</html>

```

**Comment by kbadk** [comment]
I believe this was fixed a while ago and I'm unable to reproduce. If not, feel free to reoopen.
